### ISSUE TITLE
爬虫工作不正常

### ISSUE THREAD

**Issue by marswh12312313** [Melodyknit/YanXiBot#1]
资源插件似乎爬不了资源了 每次爬取都是少量固定的资源 明显比在网站上搜索少

**Comment by MelodyKnit** [comment]
你好，因为搜索是用网站的搜索方式，会使用关键字搜索，先按照网站给出的结果分类然后会选择搜索结果中最上面的结果
例如：
天气之子
天气之子 mkv

**Comment by MelodyKnit** [comment]
这个我还没有去修复，你可以使用这个机器人的资源功能
https://github.com/Melodyknit/ClassAssistant/tree/master/src/plugins/animeres

**Comment by marswh12312313** [comment]
好的，期待修复，抱歉不能提供更多的帮助。

**Comment by marswh12312313** [comment]
另外稍微修改一下协议就能适配b1版本的bot了

**Comment by marswh12312313** [comment]
> 这个我还没有去修复，你可以使用这个机器人的资源功能 https://github.com/Melodyknit/ClassAssistant/tree/master/src/plugins/animeres

这个插件似乎对b版本也不是很适配

**Comment by MelodyKnit** [comment]
已经单独拆分出来了这个功能，您可以使用这个https://github.com/Melodyknit/nonebot_plugin_animeres
